#!/usr/bin/env perl
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Adjust index entry format in .idx file generated by \apiBk{}.
# its variants.
#
# Adjustment sample (diff):
#
# -\indexentry{smp_mb()@\lstinline [breaklines=true,breakatwhitespace=true]{smp_mb()}~{\scriptsize  (k)}|BF}{815}
# +\indexentry{smp_mb()@\lstinline [breaklines=true,breakatwhitespace=true]{smp_mb()}~{\scriptsize  (k)}|hyperindexformat{\BF}}{815}
#
# Copyright (C) Akira Yokosawa, 2024
#
# Authors: Akira Yokosawa <akiyks@gmail.com>

use strict;
use warnings;

my $line;

open(my $fh, '<:encoding(UTF-8)', $ARGV[0])
    or die "Could not open file '$ARGV[0]' $!";

while($line = <$fh>) {
    $line =~ s/\|DF\}/\|hyperindexformat\{\\DF\}\}/ ;
    $line =~ s/\|EP\}/\|hyperindexformat\{\\EP\}\}/ ;
    print $line ;
}
